let footer = $('#footer-template').html("<footer id='footer-main'></footer>")
$('#footer-main').append("<div id='footer-a'>Contact Us</div>")
    $('#footer-a').append('<p class="footer-text">1</p>')
    $('#footer-a').append('<p class="footer-text">2</p>')
    $('#footer-a').append('<p class="footer-text">3</p>')
$('#footer-main').append("<div id='footer-b'>Social Media</div>")
    $('#footer-b').append('<p class="footer-text">1</p>')
    $('#footer-b').append('<p class="footer-text">2</p>')
    $('#footer-b').append('<p class="footer-text">3</p>')
$('#footer-main').append("<div id='footer-c'>Newsletter & Press</div>")
    $('#footer-c').append('<p class="footer-text">1</p>')
    $('#footer-c').append('<p class="footer-text">2</p>')
    $('#footer-c').append('<p class="footer-text">3</p>')
$('#footer-main').append("<div id='footer-copyright'>kentaro kameyama copyright 2018</div>")
let footerTemplate = Handlebars.compile(footer)
